### ISSUE TITLE
fly.toml

### ISSUE THREAD

**Issue by mkagit** [chilir/chat-thyme#13]
Could you please help to build a fly.toml using the Docker image. And how to run more than one bot in the same Docker.

**Comment by chilir** [comment]
The Docker image is meant to be a thin wrapper around a single instance of the application process, so you wouldn't be able to run multiple instances of the app within a single container.

I'm not too familiar with fly.io, but after looking at their docs and consulting with some LLMs, I think you could try deploying two bots as two separate processes with a single deployment. There are some prerequisite steps:

* Instead of passing in a `.env` file, you would need to pass in sensitive environmental variables (such as `DISCORD_BOT_TOKEN`, `API_KEY`, etc.) as secrets using their CLI tool (i.e. `fly secrets`)
* All mount volumes need to be created using the their CLI tool beforehand in the same region (i.e. `fly volumes create <volume_name> --region <region>`)
* Each bot's config.yaml file needs to be copied their respective config volume (i.e. using `fly ssh sftp`)

```toml
# fly.toml

app = "chat-thyme-two-bots"  # rename as needed
primary_region = "iad"  # change to your region

[build]
image = "ghcr.io/chilir/chat-thyme:v0.1.0"

[processes]
bot1 = "-c /app/config/config.yaml"
bot2 = "-c /app/config/config.yaml"

[[mounts]]
source = "bot1_config"  # volume needs to be created, bot1 config.yaml file also needs to be added to this volume beforehand
destination = "/app/config"
processes = ["bot1"]

[[mounts]]
source = "bot1_logs"  # volume needs to be created beforehand
destination = "/app/logs"
processes = ["bot1"]

[[mounts]]
source = "bot1_sqlite"  # volume needs to be created beforehand
destination = "/app/.sqlite"
processes = ["bot1"]

[[mounts]]
source = "bot2_config"  #  volume needs to be created, bot2 config.yaml file also needs to be added to this volume beforehand
destination = "/app/config"
processes = ["bot2"]

[[mounts]]
source = "bot2_logs"  # volume needs to be created beforehand
destination = "/app/logs"
processes = ["bot2"]

[[mounts]]
source = "bot2_sqlite"  # volume needs to be created beforehand
destination = "/app/.sqlite"
processes = ["bot2"]

```

Like I mentioned, I've never used fly.io and I'm not familiar with their tooling, apologies in advance if this deployment configuration doesn't work out of the box. I'm not sure if I would be much help in debugging fly.io deployment issues.

Another potential way to go about it is to split the deployment into two separate deployments (one for each bot) and directly pass in chat-thyme configuration as environmental variables (sensitive ones from .env should still be added as secrets) OR command line args. This isn't well documented yet, but every configuration option in `config.yaml` can actually be set through the command line and environmental variables as well, refer to this snippet within the codebase: https://github.com/chilir/chat-thyme/blob/a286a30e276f04a3fef9c65da59a306f6e438a08/src/config/parse.ts#L156-L212
